# Question 7: LSH in ANN

In [69]:
import random
import numpy as np
import hashlib

In [2]:
def generate_dataset(n, dimension, min_value=0, max_value=100):
    
    dataset = np.random.uniform(min_value, max_value, size=(n, dimension))
    return dataset

In [5]:
def generate_hamming_dataset(n, dimension):
    dataset = np.random.randint(2, size=(n, dimension))
    return dataset

In [6]:
n_points = 1000
dimension = 32 
hamming_dataset = generate_hamming_dataset(n_points, dimension)
print(hamming_dataset)

[[1 1 0 ... 0 1 1]
 [0 1 1 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 ...
 [1 0 0 ... 1 1 0]
 [0 1 0 ... 1 0 1]
 [0 1 1 ... 1 1 1]]


In [63]:
L = 10 
z_index = np.random.randint(n_points)
z = hamming_dataset[z_index]
print("query point:", z)

query point: [1 0 1 0 0 1 1 1 0 1 0 1 0 0 0 1 1 0 1 0 1 1 0 1 0 1 1 0 0 0 1 1]


In [49]:
def hash_function_generator(num_hf):
    hash_functions = [hashlib.sha256(str(i).encode()).hexdigest() for i in range(num_hf)]
    return hash_functions

In [57]:
num_hf = 10
hashed_points = {}
hash_functions = hash_function_generator(num_hf)
for i, data_point in enumerate(hamming_dataset):
    hashed_points[i] = []
    for hf in hash_functions:
        hashed_val = int(hf, 16) % sum(bit == 1 for bit in data_point)
        hashed_points[i].append(hashed_val)

In [58]:
hashed_points

{0: [9, 3, 15, 14, 12, 7, 7, 17, 13, 17],
 1: [0, 0, 6, 8, 12, 13, 13, 14, 4, 2],
 2: [1, 12, 2, 2, 6, 11, 8, 7, 3, 7],
 3: [2, 12, 13, 7, 16, 4, 3, 8, 16, 1],
 4: [0, 0, 6, 8, 12, 13, 13, 14, 4, 2],
 5: [0, 0, 6, 8, 12, 13, 13, 14, 4, 2],
 6: [9, 3, 15, 14, 12, 7, 7, 17, 13, 17],
 7: [9, 3, 9, 2, 6, 1, 7, 5, 7, 11],
 8: [9, 11, 5, 14, 10, 13, 3, 1, 3, 7],
 9: [1, 12, 2, 2, 6, 11, 8, 7, 3, 7],
 10: [0, 0, 6, 8, 12, 13, 13, 14, 4, 2],
 11: [2, 12, 13, 7, 16, 4, 3, 8, 16, 1],
 12: [10, 7, 7, 1, 9, 8, 8, 1, 3, 1],
 13: [5, 15, 1, 18, 2, 13, 3, 9, 19, 7],
 14: [1, 12, 2, 2, 6, 11, 8, 7, 3, 7],
 15: [21, 7, 7, 12, 20, 19, 19, 1, 3, 1],
 16: [5, 15, 4, 18, 9, 3, 1, 8, 10, 11],
 17: [9, 1, 9, 0, 2, 13, 3, 11, 13, 11],
 18: [9, 3, 9, 2, 6, 1, 7, 5, 7, 11],
 19: [0, 0, 6, 8, 12, 13, 13, 14, 4, 2],
 20: [9, 11, 5, 14, 10, 13, 3, 1, 3, 7],
 21: [2, 12, 13, 7, 16, 4, 3, 8, 16, 1],
 22: [9, 3, 15, 14, 12, 7, 7, 17, 13, 17],
 23: [5, 15, 1, 18, 2, 13, 3, 9, 19, 7],
 24: [9, 3, 15, 14, 12, 7, 7, 17, 

In [66]:
candidate_points = []
z_sig = hashed_points[z_index]
for data_point, sig in hashed_points.items():
    if sig == z_sig:
        candidate_points.append(data_point)

In [68]:
len(candidate_points)

118

In [70]:
def hamming_distance(vec1, vec2):
    vec1 = np.array(vec1)
    vec2 = np.array(vec2)
    return np.sum(vec1 != vec2)

In [71]:
random_indxs = random.sample(range(len(candidate_points)), 30)
distances = {}
for i in random_indxs:
    distances[i] = hamming_distance(hamming_dataset[i], hamming_dataset[z_index])


In [73]:
sorted_items = sorted(distances.items(), key=lambda x: x[1])
min_values = sorted_items[:3]

print("Three min values:", min_values)

Three min values: [(100, 0), (20, 13), (110, 13)]
